config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  resources :projects, only: :index
  resources :comments, only: [:index, :create]

  get '/projects/:id/rendering', to: 'projects#show_rendering', as: 'project_rendering'
  get '/projects/:id/repo', to: 'projects#show_repo', as: 'project_repo'
  get '/pdfs/download_my_resume', to: 'pdfs#download_my_resume', as: 'download_my_resume'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # Associations
  has_many :comments
end

app/models/client.rb
class Client < ApplicationRecord
  # Associations
  has_many :projects
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Assoiciations
  belongs_to :comment_category

  # Validations
  validates_presence_of :comment_category, message: 'your opinion please if you don\'t mind'
  validates_presence_of :content, message: 'your comment is important for me!'

  # Instance methods
  def err_messages
    errors.messages[:comment_category].shift
    errors.messages.values.flatten.to_sentence.capitalize
  end
end

app/models/comment_category.rb
class CommentCategory < ApplicationRecord
  # Associations
  has_many :comments
end

app/models/project.rb
class Project < ApplicationRecord
  # Associations
  belongs_to :client
  has_many :taggings
  has_many :tags, through: :taggings

  # Callbacks
  before_save :set_code

  # Instance methods
  def duration_phrase
    phrase = []
    weeks = self.duration / 7
    days = self.duration % 7
    phrase << "#{weeks} #{weeks > 1 ? 'weeks' : 'week'}" if weeks > 0
    phrase << "#{days} #{days > 1 ? 'days' : 'day'}"  if days > 0
    "#{phrase.join(' and ')}."
  end
  
  def team
    "me#{self.devs > 0 ? " and #{self.devs} devs." : '.'}"
  end

  # gems setups
  extend FriendlyId
  friendly_id :code, use: :slugged

  def normalize_friendly_id(string)
    string
  end

  def should_generate_new_friendly_id?
    new_record?
  end

  private
  
  def set_code
    self.code = self.title.parameterize
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Associations
  has_many :taggings
  has_many :projects, through: :taggings

  # Callbacks
  before_save :set_code

  private
  
  def set_code
    self.code = self.title.parameterize
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(permitted_comment_params)

    if @comment.save
      flash[:success] = 'Thank you for your comment!'
    else
      flash[:alert] = @comment.err_messages
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  private

  def permitted_comment_params
    params.require(:comment).permit(:content, :comment_category_id)
  end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  def download_my_resume
    send_file(
      "#{Rails.root}/public/my_resume.pdf",
      filename: "Wazo's resume.pdf",
      type: "application/pdf"
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project, only: [:show_rendering, :show_repo]
  
  def index
    tag_ids = params[:tag_ids]
    if not tag_ids.nil?     # AJAX request, see filter.js file
      @projects = Project.joins(:taggings).where(taggings: {tag_id: tag_ids}).distinct.order(complexity: :desc, created_at: :asc)
      @selected_tags = tag_ids.map { |id| Tag.find(id) }
    else
      @projects = Project.order(complexity: :desc, created_at: :asc)
    end

    @tags = Tag.order(:order)
    
    @comment_categories = CommentCategory.all
    @comments = Comment.all
  end

  def show_rendering
    redirect_to @project.link
  end
  
  def show_repo
    redirect_to @project.git_repo
  end

  private
  
  def get_project
    @project = Project.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when 'notice' then 'alert-info'
    when 'success' then 'alert-success'
    when 'alert' then 'alert-warning'
    when 'error' then 'alert-danger'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<div class="mb-1">
  <span class="badge rounded-pill bg-success"><%= comment.comment_category.title %></span>
  <span style="font-size: 14px"><%= comment.content %></span>
</div>

app/views/comments/_comments_list.html.erb
<div id="comments-list">
  <% if @comments.count > 0 %>
    <h6 id="comments-list-title" class="mb-4">Others have left comments</h6>
    <% @comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% end %>
</div>

app/views/comments/_leave_a_comment_form.html.erb
<div id="comment-form" class="mb-5">
  <%= render 'layouts/flash' %>
  <%= form_for Comment.new, remote: true do |f| %>
    <div class="form-group mb-3">
      <%= f.label :comment_category_id, 'Your opinion!', class: 'form-label' %>
      <%= f.collection_select :comment_category_id, @comment_categories, :id, :title, {prompt: true}, {class: 'form-control form-control-sm px-2'} %>
    </div>
    <div class="mb-3">
      <%= f.text_area :content, rows: 2, placeholder: 'Leave a comment please!', class: 'form-control px-2' %>
    </div>
    <div>
      <%= f.submit 'Send', class: "btn btn-sm btn-primary" %>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$(document).ready(() => {
  let flash = document.getElementById('flash');
  let commentForm = document.getElementById('comment-form');
  let commentsList = document.getElementById('comments-list');

  <% if @comment.valid? %>
    <% if Comment.all.count == 1 %>
      commentsList.innerHTML += `<h6 id="comments-list-title" class="mb-4">Others have left comments</h6>`;
    <% end %>

    commentsList.innerHTML += `<%= j render 'comments/comment', comment: @comment %>`;

    document.getElementsByTagName('textarea')[0].value = "";
    document.getElementsByTagName('select')[0].selectedIndex = 0;
  <% end %>
  
  flash.remove();
  commentForm.insertAdjacentHTML("afterbegin", "<%= j render 'layouts/flash' %>");
  
  <% flash.clear %>
})

app/views/layouts/_flash.html.erb
<div id="flash">
  <% flash.each do |type, msg| %>
    <div class="alert alert-dismissible <%= flash_class(type) %>">
      <button type="button" class="btn-close btn-sm" data-dismiss="alert"></button>
      <div style="font-size: 14px"><%= msg%></div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<br>
<br>
<br>
<br>
<footer class="footer fixed-bottom bg-primary">
  <div class="text-white text-center py-3">Made with Rails, from scratch, without template and especially with <span style="color: red;">♥</span> <small><a href="https://github.com/b-ouinten/personal_web_site.git" class="text-muted text-decoration-none" target="_blank">view GitHub repo</a></small></div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" >
  <div class="container-fluid">
    <%= link_to 'Wazo', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a id="projects-btn" class="nav-link" href="#">My projects</a>
        </li>
        <li class="nav-item">
          <a id="about-me-btn" class="nav-link" href="#">About me</a>
        </li>
        <li class="nav-item">
          <a id="comment-me-btn" class="nav-link" href="#">Comment me</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_scroll_to_top_btn.html.erb
<button id='scroll-to-top-btn' class="btn btn-success">
  <i class="fas fa-arrow-up fa-lg"></i>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wazo Website</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">

    <%= favicon_link_tag asset_path('me-favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/scroll_to_top_btn' %>
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/ce423c8c14.js" crossorigin="anonymous"></script>
  </body>
</html>

  </body>
</html>

app/views/pdfs/download_my_resume.html.erb
<h1>Pdfs#download_my_resume</h1>
<p>Find me in app/views/pdfs/download_my_resume.html.erb</p>

app/views/projects/_about_me.html.erb
<div id="about-me" class="container-fluid bg-primary px-1 px-md-4 py-3 mb-2 mb-md-5">
  
  <h5 class="text-center text-white mb-4">About me</h5>
  <div class="row justify-content-between align-items-center about-me-text">
    <div class="col-auto">
      <div id="introduction" class="my-0"></div>
      <div id="web-presence" class="mb-3"></div>
    </div>
    <div class="col-auto">
      <div class="my-0"><small><%= link_to 'Download my resume', download_my_resume_path, class: 'text-white text-decoration-none' %></small></div>
    </div>
  </div>
</div>

app/views/projects/_banner.html.erb
<div class="banner container-fluid px-0">
  <%= image_tag 'banner.png', class: 'img-fluid' %>
  <div class="over-image half-page ">
    <p class="lead fluid-font-size text-white">Hello, my name is Brahim Ouinten but you can call me Wazo, I'm a developper fighter, I fight with my friends the Pokétechnos, the best of them is Ruby especially when he transforms into Ruby on Rails. And thanks to my friends I won several fights.</p>
    <a id="watch-projects-btn" class="h6 fluid-font-size btn btn-outline-success px-1 py-0 px-lg-2 py-lg-1 mt-lg-3" href="#" role="button">Watch my fights</a>
  </div>
</div>

app/views/projects/_comments_area.html.erb
<div id="comments-area" class="container-fluid py-3">
  <h5 class="text-center mb-4">Leave me a comment</h5>
  <div class="row">
    <div class="offset-sm-1 col-sm-10 offset-md-2 col-md-8">
      <%= render 'comments/leave_a_comment_form' %>
      <%= render 'comments/comments_list' %>
    </div>
  </div>
</div>

app/views/projects/_projects_exhibition.html.erb
<div id="projects" class="container-fluid pt-4 pt-md-5 mb-2 mb-md-5">
  <%= render 'projects_filter' %>
  <%= render 'projects_result' %>
</div>

app/views/projects/_projects_filter.html.erb
<div id="filter">
  <h5 class="text-center mb-4 fluid-font-size">Select a Pokétechnos to show the fights in which they have helped me!</h5>
  <div class="row justify-content-center">
    <% @tags.each do |tag| %>
      <div class="col-auto mb-5">
        <%= image_tag "tags_pngs/#{tag.code}.png", size: '100x100', id: tag.id, class: 'img-check img-thumbnail img-fluid border-success border-2', alt: "#{tag.title}" %>
        <div class="card-footer text-center p-0">
          <%= "Strength : #{tag.strength}/10" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_projects_result.html.erb
<div id="projects_result">
  <% if not @selected_tags.nil? %>
    <div class="row justify-content-center align-items-center fluid-font-size pt-2 mb-4">
      <div class="col-auto px-1">
        <h5 class="mb-0">Below the fights in which</h5>
      </div>
      <% @selected_tags.each do |tag| %>
        <div class="col-auto px-1">
          <%= image_tag "tags_pngs/#{tag.code}.png", size: '25x25' %>          
        </div>
      <% end %>
      <div class="col-auto px-1">
        <h5 class="mb-0">helped me!</h5>
      </div>
    </div>
  <% else %>
    <h5 class="text-center fluid-font-size pt-2 mb-4">These are all the fights!</h5>
  <% end %>
  <div class="row">
    <% @projects.each do |project| %>
      <div class="col-lg-6 mb-3">
        <div class="card mb-3 h-100">
          <%= image_tag "projects_pngs/#{project.code}.png", class: 'card-img' %>
          <div class="card-body pb-0 d-flex flex-column justify-content-between">
            <div>
              <h5 class="font-weight-bold"><%= project.title %></h5>
              <p class="card-text desciption mb-1"><%= project.description %></p>
              <div class="row">
                <div class="col-auto">
                  <p class="card-text text-muted"><small>Pokétechnos :</small></p>
                </div>
                <% project.tags.order(:order).each do |tag| %>
                  <div class="col-auto px-1">
                    <%= image_tag "tags_pngs/#{tag.code}.png", size: '15x15' %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="mb-2">
              <p class="card-text text-muted mb-0"><small>My role : <%= project.my_role  %></small></p>
              <p class="card-text text-muted mb-0"><small>Duration : <%= project.duration_phrase  %></small></p>
              <p class="card-text text-muted"><small>Team : <%= project.team %></small></p>
            </div>
          </div>
          <div class="card-footer alert-info d-flex justify-content-between align-items-center px-2 py-1 ">
            <%= link_to 'View this conquered territory', project_rendering_path(project), class: 'text-decoration-none', target: '_blank' %>
            <p class="card-text mb-0"><%= "Level : #{project.complexity}/10" %></p>
            <%= link_to 'Watch fight', project_repo_path(project), class: 'text-decoration-none', target: '_blank' %>
          </div>
        </div>
      </div>      
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'banner' %>
<%= render 'projects_exhibition' %>
<%= render 'about_me' %>
<%= render 'comments_area' %>